import entrypoints from "../../../tools/_lib/mcp-entrypoints.js";

const {
  MCP_DEPLOYMENT_ENTRYPOINT_TOKENS,
  MCP_PACKAGE_BINS,
  MCP_README_ENTRYPOINT_TOKENS,
  MCP_RUNTIME_ENTRY_SCRIPTS
} = entrypoints;

export {
  MCP_DEPLOYMENT_ENTRYPOINT_TOKENS,
  MCP_PACKAGE_BINS,
  MCP_README_ENTRYPOINT_TOKENS,
  MCP_RUNTIME_ENTRY_SCRIPTS
};
